### ISSUE TITLE
Clarify definition of CCLA in Readme.md

### ISSUE THREAD

**Issue by MarkusKuemmerle** [camaraproject/EasyCLA#21]
The sentence
•	If contributing on behalf of their company: the contributor will sign a Corporate Contributor License (CCLA).
is not clear.

Isn't it the case that
- the CLA manager signs the CCLA for the company
- then each contributor from that company signs their CLA referencing the CCLA?

**Comment by hdamker** [comment]
@MarkusKuemmerle the sentence is 1:1 from the EasyCLA documentation at https://docs.linuxfoundation.org/lfx/easycla/v2-current/contributors. If you think it should be changed we should start there.

My understanding of the sentence: If someone is "contributing on behalf of their company", the contributor is actually the company and the company will sign a CCLA. But I agree it can be written more clearly.

cc: @wrathwolf

**Comment by MarkusKuemmerle** [comment]
I would distinguish between
- Signing for the company (one time) and
- Signing for each contributor of a company referencing the above

What is the correct naming for both to make it very clear and explicit?

**Comment by hdamker** [comment]
> * Signing for each contributor of a company referencing the above

The contributor you is contributing on behalf of the company who has signed a CCLA does not sign anything. They select only their company in the process and the CLA Manager approves that the person is allowed to contribute on behalf of the company (that can be done in advance, even for all employees with company.com email address at once).

**Comment by hdamker** [comment]
What about the following proposal:

* If contributing on behalf of their company: the contributor's company will sign or have already signed a Corporate Contributor License (CCLA) and authorizes the contributor to contribute on behalf of the company.

**Comment by MarkusKuemmerle** [comment]
What about that:

- If contributing on behalf of their company: The contributor's company will sign or have already signed a Corporate Contributor License (CCLA). The contributor has to get an authorization from his/her company's CLA manager to contribute on behalf of the company.

**Comment by hdamker** [comment]
@MarkusKuemmerle this is fixed with #23, right? So we can close the issue.

**Comment by hdamker** [comment]
I propose to simplify our initial solution again and derive the text from https://docs.linuxfoundation.org/v2/easycla/getting-started#contributor:

> identify the company on whose behalf they are contributing, so that they can either be authorized under a signed CCLA or else start the CCLA signing process.

Will create the PR to fix the issue finally.

**Comment by MarkusKuemmerle** [comment]
Sounds fantastic
